port: 8082

admin:
  email: support@nure.ua
  firstName: admin
  lastName: admin
  textColor: #FF0000
  password: password

database:
  username: postgres
  password: 12345
  host: localhost
  port: 5432
  dbname: postgres
  sslmode: disable